export type Permission =
  | 'patients.read'
  | 'patients.write'
  | 'patients.delete'
  | 'orders.read'
  | 'orders.write'
  | 'orders.delete'
  | 'billing.read'
  | 'billing.write'
  | 'files.upload'
  | 'files.read'
  | 'files.delete'
  | 'clinic.manage'
  | 'lab.manage'
  | 'staff.manage'
  | 'cad.access'
